//! Pure payload builders for packets generated by this device.
//!
//! Each module builds the portnum-specific proto bytes. The caller
//! (`mesh_task`) passes them to `lora_send()` which handles the common
//! encrypt → PacketHeader → RadioFrame → TX pipeline.

pub mod node_info;
pub mod telemetry;
